{% set version = "7.0.0b0" %}
{% set lab_version = ">=4.0.0b0,<5" %}

package:
  name: notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: efb6e3fd91ad20636c615430ddebf4fc3bd56904419bc88f439732945641b2e8

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  number: 0
  entry_points:
    - jupyter-notebook = notebook.app:main

requirements:
  host:
    - hatch-jupyter-builder >=0.2
    - hatchling >=1.11
    - jupyterlab {{ lab_version }}
    - pip
    - python >=3.8
  run:
    - importlib-resources >=5.0
    - jupyter_server >=2.0.1,<3
    - jupyterlab {{ lab_version }}
    - jupyterlab_server >=2.19.0,<3
    - notebook-shim >=0.2,<0.3
    - python >=3.8
    - tornado >=6.2.0

test:
  requires:
    - pip
    - m2-grep  # [win]
  commands:
    - pip check
    - jupyter notebook -h
    - jupyter-notebook -h
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@jupyter-notebook/lab-extension.*OK" labextensions
  imports:
    - notebook

about:
  home: https://github.com/jupyter/notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file: 
    - LICENSE
    - notebook/labextension/static/third-party-licenses.json
    # TODO: upstream issue
    # - notebook/static/third-party-licenses.json
  summary: A web-based notebook environment for interactive computing
  doc_url: https://jupyter-notebook.readthedocs.io
  doc_source_url: https://github.com/jupyter/notebook/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
    - lresende
    - bollwyvl
    - blink1073
    - davidbrochart
