{% set version = "6.1.2" %}

package:
  name: notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: 21c38373a8cc179c65b4e49172c7a3af712c42a0be237d811287680a6c8b9ad6

build:
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
    - find {{ PREFIX }} -name '*.js.map' -delete  # [not win]
  number: 0
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main
    - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.6.1
    - jupyter_client >=5.3.4
    - nbconvert
    - nbformat
    - python
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.1
    - tornado >=5.0
    - traitlets >=4.2.1
    - prometheus_client
    - argon2-cffi

test:
  requires:
    - pip
    - requests
  commands:
    - python -m pip check
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
    - jupyter bundlerextension -h
  imports:
    - notebook
    - notebook.tests.launchnotebook

about:
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
  dev_url: https://github.com/jupyter/notebook
  doc_url: https://jupyter-notebook.readthedocs.io
  doc_source_url: https://github.com/jupyter/notebook/tree/master/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
    - lresende
    - bollwyvl
    - blink1073
