{% set version = "5.7.11" %}

package:
  name: notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: 71ec4d470c60d7251cd1244ea30d848dd0cb9a6da2630e4f2ce62b38d0a343f6

build:
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  number: 0
  entry_points:
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-serverextension = notebook.serverextensions:main
    - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main

requirements:
  host:
    - python
    - pip
  run:
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_core >=4.4.0
    - jupyter_client >=5.2.0
    - nbconvert <6.0
    - nbformat
    - python
    - pyzmq >=17
    - send2trash
    - terminado >=0.8.1
    - tornado >=4.1,<7
    - traitlets >=4.2.1
    - prometheus_client
    - ipaddress  # [py2k]

test:
  commands:
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
    - jupyter bundlerextension -h
  imports:
    - notebook

about:
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: A web-based notebook environment for interactive computing

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
