{% set version = "7.0.0a17" %}

package:
  name: notebook
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/notebook/notebook-{{ version }}.tar.gz
  sha256: cf2e5855e07a7b8c08efbeae23643deb29814858d26940a772274365f371a343

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  number: 0
  entry_points:
    - jupyter-notebook = notebook.app:main

requirements:
  host:
    - hatchling >=1.11
    - jupyterlab >=4.0.0a37,<5
    - pip
    - python >=3.8
  run:
    - importlib-resources >=5.0
    - jupyter_server >=2.0.1,<3
    - jupyterlab >=4.0.0a37,<5
    - jupyterlab_server >=2.19.0,<3
    - notebook_shim >=0.2,<0.3
    - python >=3.8
    - tornado >=6.2.0

test:
  requires:
    - pip
  commands:
    - python -m pip check
    - jupyter notebook -h
  imports:
    - notebook

about:
  home: https://github.com/jupyter/notebook
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
  doc_url: https://jupyter-notebook.readthedocs.io
  doc_source_url: https://github.com/jupyter/notebook/tree/v{{ version }}/docs

extra:
  recipe-maintainers:
    - SylvainCorlay
    - jakirkham
    - minrk
    - pelson
    - gnestor
    - takluyver
    - lresende
    - bollwyvl
    - blink1073
    - davidbrochart
